language: smalltalk
sudo: false

aliases:
  - &pharo4-has-latest-metacello
    smalltalk_config: .pharo4.ston

matrix:
  allow_failures:
    - smalltalk: Squeak-trunk
    - smalltalk: Squeak-5.1
 
  include:
    - smalltalk: Pharo64-7.0
      env: BUILD_NAME=Pharo64-7.0
    - smalltalk: Pharo64-6.1
      env: BUILD_NAME=Pharo64-6.1
    - smalltalk: Pharo-6.1
      env: BUILD_NAME=Pharo-6.1
    - smalltalk: Pharo-5.0
      env: BUILD_NAME=Pharo-5.0
    - smalltalk: Pharo-4.0
      <<: *pharo4-has-latest-metacello
      env: BUILD_NAME=Pharo-4.0
    - smalltalk: Squeak-trunk
      env: BUILD_NAME=Squeak-trunk
    - smalltalk: Squeak-5.2
      env: BUILD_NAME=Squeak-5.2
    - smalltalk: Squeak-5.1
      env: BUILD_NAME=Squeak-5.1
    - smalltalk: GemStone-3.4.2
      env: BUILD_NAME=GemStone-3.4.2
    - smalltalk: GemStone-3.3.4
      env: BUILD_NAME=GemStone-3.3.4
    - smalltalk: GemStone-3.2.16
      env: BUILD_NAME=GemStone-3.2.16
    - smalltalk: GemStone-3.1.0.6
      env: BUILD_NAME=GemStone-3.1.0.6
    - smalltalk: GemStone-2.4.8
      env: BUILD_NAME=GemStone-2.4.8

cache:
  directories:
    - $SMALLTALK_CI_CACHE